import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Lang = "ru" | "en" | "es";

const translations: Record<Lang, Record<string, string>> = {
  ru: {
    "settings": "Настройки",
    "settings.desc": "Управление аккаунтом, внешним видом и настройками.",
    "settings.profile": "Профиль",
    "settings.appearance": "Внешний вид",
    "settings.notifications": "Уведомления",
    "settings.privacy": "Приватность",
    "settings.data": "Данные",
    "settings.license": "Лицензия",
    "settings.about": "О нас",
    "settings.language": "Язык",
    "profile.title": "Ваш профиль",
    "profile.desc": "Ваша личность Roblox и присутствие в сообществе.",
    "profile.bio": "Био для сообщества",
    "profile.bio.placeholder": "Расскажите другим разработчикам о себе...",
    "profile.bio.save": "Сохранить био",
    "profile.bio.saved": "Био сохранено!",
    "profile.bio.saved.desc": "Ваш профиль в сообществе обновлён.",
    "profile.view": "Смотреть на Roblox ↗",
    "profile.session": "Действия с сессией",
    "profile.disconnect": "Отключить аккаунт Roblox",
    "profile.revoke": "Отозвать лицензионный ключ",
    "appearance.theme": "Тема",
    "appearance.theme.desc": "Выберите, как выглядит Limited.Ink для вас.",
    "appearance.light": "Светлая",
    "appearance.dark": "Тёмная",
    "appearance.system": "Система",
    "appearance.active": "Активна",
    "appearance.interface": "Интерфейс",
    "appearance.compact": "Компактный режим",
    "appearance.compact.desc": "Уменьшить отступы для большего контента на экране.",
    "appearance.autorefresh": "Авто-обновление продаж",
    "appearance.autorefresh.desc": "Автоматически обновлять данные продаж каждые 30 секунд.",
    "notif.title": "Уведомления",
    "notif.desc": "Настройте способ уведомлений.",
    "notif.sound": "Звуковые эффекты",
    "notif.sound.desc": "Воспроизводить звуки для действий и событий.",
    "notif.sound.test": "Тест",
    "notif.upload": "Уведомления о загрузке",
    "notif.upload.desc": "Показывать уведомления при загрузке одежды.",
    "notif.chat": "Уведомления чата",
    "notif.chat.desc": "Показывать уведомления о новых сообщениях.",
    "privacy.title": "Приватность",
    "privacy.desc": "Управление вашей видимостью на платформе.",
    "privacy.discover": "Показывать профиль в Обзоре",
    "privacy.discover.desc": "Позволить другим разработчикам находить вас во вкладке Сообщество.",
    "privacy.groups": "Показывать мои группы",
    "privacy.groups.desc": "Отображать ваши группы Roblox в профиле сообщества.",
    "privacy.friends": "Разрешить запросы в друзья",
    "privacy.friends.desc": "Позволить другим отправлять вам запросы в друзья.",
    "privacy.security": "Информация о безопасности",
    "privacy.cookie": "Безопасность Cookie",
    "privacy.cookie.desc": "Ваш Roblox cookie хранится в зашифрованной серверной сессии (PostgreSQL, 7 дней) и удаляется при отключении.",
    "privacy.protected": "Защита лицензией",
    "privacy.protected.desc": "Все API-эндпоинты защищены вашим лицензионным ключом. Неавторизованный доступ заблокирован.",
    "data.export": "Экспорт данных",
    "data.export.desc": "Скачайте копию ваших настроек и сохранённых данных.",
    "data.export.btn": "Экспортировать данные (JSON)",
    "data.exported": "Экспортировано!",
    "data.exported.desc": "Ваши данные сохранены как JSON файл.",
    "data.local": "Локальное хранилище",
    "data.local.desc": "Управление данными на этом устройстве.",
    "data.prefs": "Настройки интерфейса",
    "data.prefs.desc": "Тема, состояния вкладок и другое",
    "data.reset": "Сбросить",
    "data.cleared": "Очищено",
    "data.cleared.desc": "Настройки интерфейса были сброшены.",
    "license.title": "Информация о лицензии",
    "license.desc": "Детали вашего текущего плана Limited.Ink.",
    "license.plan": "План",
    "license.status": "Статус",
    "license.active": "Активна",
    "license.invalid": "Недействительна",
    "license.expires": "Истекает",
    "license.upgrade": "Улучшить план",
    "license.upgrade.desc": "Получите доступ к большему количеству функций с более высоким тарифом.",
    "about.version": "Версия",
    "about.env": "Среда",
    "about.footer": "Limited.Ink — Профессиональная платформа управления группами Roblox",
    "lang.title": "Язык интерфейса",
    "lang.desc": "Выберите язык для интерфейса Limited.Ink.",
    "lang.ru": "Русский",
    "lang.en": "English",
    "lang.es": "Español",
    "characters": "символов",

    "nav.profile": "Мой профиль",
    "nav.community": "Сообщество",
    "nav.tools": "Инструменты",
    "nav.assistant": "AI Ассистент",
    "nav.competitors": "Конкуренты",
    "nav.sniper": "Снайпер лимиток",
    "nav.groups": "Ваши группы",
    "nav.settings": "Настройки",
    "nav.license": "Лицензия",
    "nav.disconnect": "Отключить",
    "nav.revoke": "Отозвать",
    "nav.members": "участников",
    "nav.noGroups": "Групп не найдено.",

    "home.welcome": "Добро пожаловать в",
    "home.subtitle": "Выберите группу из боковой панели — статистика, каталог, аналитика и многое другое.",
    "home.groupMgmt": "Управление группами",
    "home.catalogBrowser": "Каталог",
    "home.salesAnalytics": "Аналитика продаж",
    "home.featured": "Избранные группы",
    "home.featured.desc": "Группы Roblox, работающие на Limited.Ink",
    "home.noFeatured": "Пока нет избранных групп",
    "home.noFeatured.desc": "Группы, активно использующие Limited.Ink, появятся здесь.",
    "home.members": "Участники",
    "home.access": "Доступ",
    "home.public": "Открытый",
    "home.private": "Закрытый",
    "home.unknown": "Неизвестно",
    "home.owner": "Владелец",
    "home.created": "Создано",
    "home.openRoblox": "Открыть на Roblox",
    "home.failedLoad": "Не удалось загрузить информацию о группе",

    "activation.title": "Активируйте лицензию",
    "activation.desc": "Получите код от Telegram-бота и введите его ниже.",
    "activation.step1": "Откройте Telegram",
    "activation.step1.desc": "Найдите нашего официального бота",
    "activation.step2": "Отправьте /activate",
    "activation.step2.desc": "Запросите код лицензии",
    "activation.step3": "Введите код ниже",
    "activation.step3.desc": "Вставьте и активируйте",
    "activation.botLink": "Откройте бота и напишите /activate",
    "activation.activate": "Активировать устройство",
    "activation.verifying": "Проверка...",
    "activation.success": "Лицензия активирована",
    "activation.failed": "Ошибка активации",
    "activation.terms": "Активируя, вы соглашаетесь с Условиями использования и Политикой конфиденциальности.",
    "activation.platform": "Профессиональная платформа Roblox",
    "activation.tagline": "Управление каталогом, инструменты для одежды и аналитика продаж — всё в одном месте.",
    "activation.features.catalog": "Копирование каталога",
    "activation.features.analytics": "Аналитика продаж",
    "activation.features.alts": "Менеджер альтов",
    "activation.features.featured": "Избранные группы",

    "roblox.connect": "Подключить Roblox",
    "roblox.desc": "Cookie сессии позволяет нам управлять группами и загружать одежду от вашего имени.",
    "roblox.howTo": "Как получить cookie",
    "roblox.step1": "Откройте Roblox",
    "roblox.step1.desc": "Перейдите на roblox.com и войдите",
    "roblox.step2": "F12 → Application",
    "roblox.step2.desc": "Откройте DevTools, нажмите \"Application\"",
    "roblox.step3": "Найдите .ROBLOSECURITY",
    "roblox.step3.desc": "Cookies → roblox.com → скопируйте значение",
    "roblox.connectBtn": "Подключить аккаунт",
    "roblox.connecting": "Подключение...",
    "roblox.connected": "Подключено!",
    "roblox.connectedAs": "Вы вошли как",
    "roblox.failed": "Ошибка подключения",
    "roblox.security": "Ваш cookie отправляется напрямую на сервер и не хранится в браузере. Сессия истекает через 7 дней.",
    "roblox.privacy.title": "Ваши данные защищены.",
    "roblox.privacy.desc": "Мы запрашиваем минимальные разрешения для управления группами и загрузки одежды.",
    "roblox.privacy.1": "Cookie не хранится в браузере",
    "roblox.privacy.2": "Зашифрованная серверная сессия",
    "roblox.privacy.3": "Автоматически истекает через 7 дней",
    "roblox.privacy.4": "Отзовите доступ в любое время в Настройках",

    "profile.friends": "Друзья",
    "profile.followers": "Подписчики",
    "profile.following": "Подписки",
    "profile.verified": "Подтверждён",
    "profile.banned": "Забанен",
    "profile.openRoblox": "Открыть в Roblox ↗",
    "profile.about": "О себе",
    "profile.created": "Аккаунт создан",
    "profile.failedLoad": "Не удалось загрузить профиль.",

    "sniper.title": "Снайпер лимиток",
    "sniper.desc": "Мониторинг и покупка лимитированных предметов Roblox",
    "sniper.browse": "Обзор",
    "sniper.deals": "Сделки",
    "sniper.watchlist": "Отслеживание",
    "sniper.search": "Поиск лимиток...",
    "sniper.searchBtn": "Поиск",
    "sniper.deals.desc": "Предметы, чья стоимость выше RAP или прогнозируется к росту",
    "sniper.refresh": "Обновить",
    "sniper.watchlist.title": "Список отслеживания",
    "sniper.watchlist.desc": "Отслеживайте предметы и проверяйте цены для покупки.",
    "sniper.checkPrices": "Проверить цены",
    "sniper.pricesUpdated": "Цены обновлены",
    "sniper.addItems": "Добавьте предметы из Обзора или Сделок для отслеживания.",
    "sniper.target": "Цель",
    "sniper.live": "Цена",
    "sniper.notForSale": "Не продаётся",
    "sniper.buy": "Купить",
    "sniper.purchased": "Куплено!",
    "sniper.purchaseFailed": "Ошибка покупки",

    "competitors.title": "Анализ конкурентов",
    "competitors.desc": "Анализируйте любую группу Roblox для изучения стратегии",
    "competitors.placeholder": "Введите ID группы конкурента (например 114200141)",
    "competitors.analyze": "Анализ",
    "competitors.members": "Участники",
    "competitors.clothingItems": "Предметы одежды",
    "competitors.avgPrice": "Сред. цена",
    "competitors.totalFavorites": "Всего избранных",
    "competitors.breakdown": "Разбивка по одежде",
    "competitors.shirts": "Рубашки",
    "competitors.pants": "Штаны",
    "competitors.tshirts": "Футболки",
    "competitors.priceAnalytics": "Аналитика цен",
    "competitors.medianPrice": "Медианная цена",
    "competitors.minPrice": "Мин. цена",
    "competitors.maxPrice": "Макс. цена",
    "competitors.avgFavorites": "Сред. избранных",
    "competitors.created": "Создано",
    "competitors.freeVsPaid": "Бесплатные vs Платные",
    "competitors.paid": "Платные",
    "competitors.freeOffsale": "Бесплатные / Не в продаже",
    "competitors.priceDist": "Распределение цен",
    "competitors.free": "Бесплатно",
    "competitors.top5": "Топ-5 популярных",
    "competitors.topClothing": "Топ одежды",
    "competitors.allClothing": "Вся одежда",
    "competitors.showTop15": "Показать топ 15",
    "competitors.showAll": "Показать все",
    "competitors.loadMore": "Загрузить ещё",
    "competitors.remaining": "осталось",
    "competitors.noItems": "Предметы не найдены",
    "competitors.open": "Открытая",
    "competitors.closed": "Закрытая",
    "competitors.byFavorites": "По избранным",
    "competitors.all": "Все",
    "competitors.offsale": "Не в продаже",

    "community.feed": "Лента",
    "community.discover": "Обзор",
    "community.friends": "Друзья",
    "community.messages": "Сообщения",
    "community.title": "Сообщество",
    "community.desc": "Общайтесь с другими разработчиками Roblox",
    "community.newPost": "Что нового?",
    "community.post": "Опубликовать",
    "community.comment": "Комментарий",
    "community.comments": "Комментарии",
    "community.noComments": "Комментариев пока нет. Будьте первым!",
    "community.writeComment": "Написать комментарий...",
    "community.addFriend": "Добавить в друзья",
    "community.friendsCheck": "Друзья ✓",
    "community.requestSent": "Запрос отправлен",
    "community.acceptRequest": "Принять запрос",
    "community.friendSent": "Запрос в друзья отправлен!",
    "community.unfriended": "Удалён из друзей",
    "community.friendAdded": "Друг добавлен!",
    "community.chat": "Чат",
    "community.viewRoblox": "Смотреть на Roblox",
    "community.groups": "Группы",
    "community.posts": "Посты",
    "community.noShared": "Этот разработчик ещё ничем не поделился.",
    "community.profileNotFound": "Профиль не найден",
    "community.noPosts": "Постов пока нет. Напишите что-нибудь!",
    "community.searchUsers": "Поиск разработчиков...",
    "community.noUsersFound": "Пользователи не найдены",
    "community.noFriends": "Нет друзей. Отправьте запрос во вкладке Обзор!",
    "community.noMessages": "Нет сообщений. Начните общение с друзьями!",
    "community.typeMessage": "Введите сообщение...",
    "community.you": "Вы",
    "community.pending": "Ожидание",
    "community.accept": "Принять",
    "community.loading": "Настраиваем ваш профиль...",
    "community.forum": "Форум",
    "community.editBio": "Редактировать био",

    "assistant.title": "AI Ассистент",
    "assistant.desc": "Эксперт по Roblox к вашим услугам",
    "assistant.clear": "Очистить",
    "assistant.askAnything": "Спросите меня о Roblox",
    "assistant.capabilities": "Lua скрипты, модерация, стратегии одежды, посты для Discord — я помогу со всем.",
    "assistant.placeholder": "Спросите что угодно о Roblox...",
    "assistant.error": "Произошла ошибка. Попробуйте снова.",
    "assistant.chatMode": "Чат",
    "assistant.imageMode": "Изображение",
    "assistant.imagePlaceholder": "Опишите изображение...",
    "assistant.generating": "Генерирую изображение...",
    "assistant.downloadImage": "Скачать",
    "assistant.imageAttached": "Изображение прикреплено",
    "assistant.attachImage": "Прикрепить фото",

    "sniper.catalogPrice": "Каталог",

    "group.overview": "Обзор",
    "group.catalog": "Каталог",
    "group.clothing": "Одежда",
    "group.upload": "Загрузка",
    "group.alts": "Альты",
    "group.pnl": "P&L",
    "group.stats": "Статистика группы",
    "group.funds": "Фонды",
    "group.pending": "В ожидании",
    "group.revenue24h": "Доход 24ч",
    "group.sales24h": "Продажи 24ч",
    "group.joinPolicy": "Политика вступления",
    "group.locked": "Заблокирована",
    "group.notLocked": "Не заблокирована",
    "group.members": "участников",
    "group.catalogSearch": "Поиск по каталогу",
    "group.catalogSearch.desc": "Ищите одежду на Roblox, копируйте или скачивайте шаблоны.",
    "group.keyword": "Ключевое слово...",
    "group.groupIdFilter": "ID группы",
    "group.search": "Поиск",
    "group.results": "результатов",
    "group.selected": "выбрано",
    "group.download": "Скачать",
    "group.selectAll": "Выбрать все",
    "group.clear": "Очистить",
    "group.copy": "Копировать",
    "group.copied": "Скопировано!",
    "group.copyFailed": "Ошибка копирования",
    "group.downloadFailed": "Ошибка скачивания",
    "group.bulkDownload": "Массовое скачивание",
    "group.noResults": "Нет результатов",
    "group.tryDifferent": "Попробуйте другое ключевое слово или ID группы.",
    "group.slowDown": "Подождите",
    "group.slowDown.desc": "Подождите несколько секунд между поисками.",
    "group.searchFailed": "Ошибка поиска",
    "group.shirts": "Рубашки",
    "group.pants": "Штаны",
    "group.relevance": "Релевантность",
    "group.mostFavourited": "Популярные",
    "group.bestselling": "Бестселлеры",
    "group.recentlyUpdated": "Недавние",
    "group.clothingTab": "Одежда группы",
    "group.clothingTab.desc": "Одежда, созданная вашей группой.",
    "group.uploadTab": "Загрузка одежды",
    "group.uploadTab.desc": "Загрузите одежду в вашу группу.",
    "group.uploadName": "Название",
    "group.uploadDesc": "Описание",
    "group.uploadType": "Тип",
    "group.uploadPrice": "Цена",
    "group.uploadBtn": "Загрузить",
    "group.uploading": "Загрузка...",
    "group.uploadSuccess": "Загружено!",
    "group.uploadFailed": "Ошибка загрузки",
    "group.uploadAccount": "Аккаунт для загрузки",
    "group.mainAccount": "Основной аккаунт",
    "group.bulkName": "Общее название",
    "group.bulkType": "Общий тип",
    "group.bulkPrice": "Общая цена",
    "group.bulkDesc": "Общее описание",
    "group.apply": "Применить",
    "group.template": "Шаблон",
    "group.removeTemplate": "Удалить шаблон",
    "group.altsTab": "Альт-аккаунты",
    "group.altsTab.desc": "Управляйте альтернативными аккаунтами в группе.",
    "group.addAlt": "Добавить альт",
    "group.removeAlt": "Удалить альт",
    "group.refreshAlts": "Обновить",

    "pnl.title": "Прибыли и убытки",
    "pnl.revenue": "Выручка",
    "pnl.sales": "Продажи",
    "pnl.period": "Период",
    "pnl.daily": "За день",
    "pnl.weekly": "За неделю",
    "pnl.monthly": "За месяц",
    "pnl.noData": "Нет данных за выбранный период.",
    "pnl.balance": "Баланс",
    "pnl.pending": "В ожидании",
    "pnl.today": "Сегодня",
    "pnl.net7d": "Чистая (7д)",
    "pnl.weekRevenue": "Выручка за неделю",
    "pnl.commission": "Комиссия Roblox (30%)",
    "pnl.netFiat": "Чистая в фиате",
    "pnl.monthRevenue": "Выручка за месяц",
    "pnl.monthLabel": "месяц",
    "pnl.topItems": "Топ предметов по выручке",
    "pnl.recentTx": "Последние транзакции",
    "group.failedLoad": "Не удалось загрузить данные группы.",
  },
  en: {
    "settings": "Settings",
    "settings.desc": "Manage your account, appearance, and preferences.",
    "settings.profile": "Profile",
    "settings.appearance": "Appearance",
    "settings.notifications": "Notifications",
    "settings.privacy": "Privacy & Security",
    "settings.data": "Data & Storage",
    "settings.license": "License",
    "settings.about": "About",
    "settings.language": "Language",
    "profile.title": "Your Profile",
    "profile.desc": "Your Roblox identity and community presence.",
    "profile.bio": "Community Bio",
    "profile.bio.placeholder": "Tell other developers about yourself...",
    "profile.bio.save": "Save Bio",
    "profile.bio.saved": "Bio saved!",
    "profile.bio.saved.desc": "Your community profile has been updated.",
    "profile.view": "View on Roblox ↗",
    "profile.session": "Session Actions",
    "profile.disconnect": "Disconnect Roblox Account",
    "profile.revoke": "Revoke License Key",
    "appearance.theme": "Theme",
    "appearance.theme.desc": "Choose how Limited.Ink looks for you.",
    "appearance.light": "Light",
    "appearance.dark": "Dark",
    "appearance.system": "System",
    "appearance.active": "Active",
    "appearance.interface": "Interface",
    "appearance.compact": "Compact Mode",
    "appearance.compact.desc": "Reduce spacing for more content on screen.",
    "appearance.autorefresh": "Auto-refresh Sales",
    "appearance.autorefresh.desc": "Automatically refresh sales data every 30 seconds.",
    "notif.title": "Notifications",
    "notif.desc": "Control how you get notified.",
    "notif.sound": "Sound Effects",
    "notif.sound.desc": "Play sounds for actions and events.",
    "notif.sound.test": "Test",
    "notif.upload": "Upload Notifications",
    "notif.upload.desc": "Show toast notifications for clothing uploads.",
    "notif.chat": "Chat Notifications",
    "notif.chat.desc": "Show notifications for new messages.",
    "privacy.title": "Privacy",
    "privacy.desc": "Control your visibility on the platform.",
    "privacy.discover": "Show Profile in Discover",
    "privacy.discover.desc": "Let other developers find you in the Community tab.",
    "privacy.groups": "Show My Groups",
    "privacy.groups.desc": "Display your Roblox groups on your community profile.",
    "privacy.friends": "Allow Friend Requests",
    "privacy.friends.desc": "Let others send you friend requests.",
    "privacy.security": "Security Info",
    "privacy.cookie": "Cookie Security",
    "privacy.cookie.desc": "Your Roblox cookie is stored in an encrypted server session (PostgreSQL-backed, 7-day TTL) and is cleared when you disconnect.",
    "privacy.protected": "License Protected",
    "privacy.protected.desc": "All API endpoints are protected by your license key. Unauthorized access is blocked.",
    "data.export": "Export Your Data",
    "data.export.desc": "Download a copy of your settings and saved prompts.",
    "data.export.btn": "Export Data as JSON",
    "data.exported": "Exported!",
    "data.exported.desc": "Your data has been saved as a JSON file.",
    "data.local": "Local Storage",
    "data.local.desc": "Manage data stored locally on this device.",
    "data.prefs": "UI Preferences",
    "data.prefs.desc": "Theme, tab states, and more",
    "data.reset": "Reset",
    "data.cleared": "Cleared",
    "data.cleared.desc": "UI preferences have been reset.",
    "license.title": "License Information",
    "license.desc": "Details about your current Limited.Ink plan.",
    "license.plan": "Plan",
    "license.status": "Status",
    "license.active": "Active",
    "license.invalid": "Invalid",
    "license.expires": "Expires",
    "license.upgrade": "Upgrade Your Plan",
    "license.upgrade.desc": "Get access to more features with a higher tier plan.",
    "about.version": "Version",
    "about.env": "Environment",
    "about.footer": "Limited.Ink — Professional Roblox Group Management Platform",
    "lang.title": "Interface Language",
    "lang.desc": "Choose the language for the Limited.Ink interface.",
    "lang.ru": "Русский",
    "lang.en": "English",
    "lang.es": "Español",
    "characters": "characters",

    "nav.profile": "My Profile",
    "nav.community": "Community",
    "nav.tools": "Tools",
    "nav.assistant": "AI Assistant",
    "nav.competitors": "Competitors",
    "nav.sniper": "Limited Sniper",
    "nav.groups": "Your Groups",
    "nav.settings": "Settings",
    "nav.license": "License",
    "nav.disconnect": "Disconnect",
    "nav.revoke": "Revoke",
    "nav.members": "members",
    "nav.noGroups": "No owned groups found.",

    "home.welcome": "Welcome to",
    "home.subtitle": "Select a group from the sidebar to manage it — stats, catalog, analytics and more.",
    "home.groupMgmt": "Group management",
    "home.catalogBrowser": "Catalog browser",
    "home.salesAnalytics": "Sales analytics",
    "home.featured": "Featured Groups",
    "home.featured.desc": "Roblox groups currently running on Limited.Ink",
    "home.noFeatured": "No featured groups yet",
    "home.noFeatured.desc": "Groups that actively use Limited.Ink will appear here.",
    "home.members": "Members",
    "home.access": "Access",
    "home.public": "Public",
    "home.private": "Private",
    "home.unknown": "Unknown",
    "home.owner": "Owner",
    "home.created": "Created",
    "home.openRoblox": "Open on Roblox",
    "home.failedLoad": "Failed to load group info",

    "activation.title": "Activate your license",
    "activation.desc": "Get your code from the Telegram bot, then enter it below.",
    "activation.step1": "Open Telegram",
    "activation.step1.desc": "Find our official bot",
    "activation.step2": "Send /activate",
    "activation.step2.desc": "Request your license code",
    "activation.step3": "Enter code below",
    "activation.step3.desc": "Paste and activate",
    "activation.botLink": "Open bot and type /activate",
    "activation.activate": "Activate Device",
    "activation.verifying": "Verifying...",
    "activation.success": "License Activated",
    "activation.failed": "Activation Failed",
    "activation.terms": "By activating, you agree to our Terms of Service and Privacy Policy.",
    "activation.platform": "Professional Roblox Platform",
    "activation.tagline": "Catalog management, clothing tools, and sales analytics — all in one place.",
    "activation.features.catalog": "Catalog Copy Tool",
    "activation.features.analytics": "Sales Analytics",
    "activation.features.alts": "Alt Account Manager",
    "activation.features.featured": "Featured Groups",

    "roblox.connect": "Connect Roblox",
    "roblox.desc": "Your session cookie lets us manage groups and upload clothing on your behalf.",
    "roblox.howTo": "How to get your cookie",
    "roblox.step1": "Open Roblox",
    "roblox.step1.desc": "Go to roblox.com and log in",
    "roblox.step2": "F12 → Application",
    "roblox.step2.desc": "Open DevTools, click \"Application\"",
    "roblox.step3": "Find .ROBLOSECURITY",
    "roblox.step3.desc": "Cookies → roblox.com → copy value",
    "roblox.connectBtn": "Connect Account",
    "roblox.connecting": "Connecting...",
    "roblox.connected": "Connected!",
    "roblox.connectedAs": "Signed in as",
    "roblox.failed": "Connection failed",
    "roblox.security": "Your cookie is sent directly to our server and never stored in the browser. Session expires automatically in 7 days.",
    "roblox.privacy.title": "Your data stays private.",
    "roblox.privacy.desc": "We only request the minimum permissions needed to manage your Roblox groups and upload clothing assets.",
    "roblox.privacy.1": "Cookie never stored in your browser",
    "roblox.privacy.2": "Encrypted server-side session",
    "roblox.privacy.3": "Automatically expires in 7 days",
    "roblox.privacy.4": "Revoke access anytime from Settings",

    "profile.friends": "Friends",
    "profile.followers": "Followers",
    "profile.following": "Following",
    "profile.verified": "Verified",
    "profile.banned": "Banned",
    "profile.openRoblox": "Open in Roblox ↗",
    "profile.about": "About",
    "profile.created": "Account created",
    "profile.failedLoad": "Failed to load profile.",

    "sniper.title": "Limited Sniper",
    "sniper.desc": "Monitor and snipe Roblox limited items",
    "sniper.browse": "Browse",
    "sniper.deals": "Deals",
    "sniper.watchlist": "Watchlist",
    "sniper.search": "Search limiteds...",
    "sniper.searchBtn": "Search",
    "sniper.deals.desc": "Items with value higher than RAP or projected to rise",
    "sniper.refresh": "Refresh",
    "sniper.watchlist.title": "Watchlist",
    "sniper.watchlist.desc": "Track items and check live prices to snipe deals.",
    "sniper.checkPrices": "Check Prices",
    "sniper.pricesUpdated": "Prices updated",
    "sniper.addItems": "Add items from Browse or Deals to watch them.",
    "sniper.target": "Target",
    "sniper.live": "Live",
    "sniper.notForSale": "Not for sale",
    "sniper.buy": "Buy",
    "sniper.purchased": "Purchased!",
    "sniper.purchaseFailed": "Purchase failed",

    "competitors.title": "Competitor Tracker",
    "competitors.desc": "Analyze any Roblox group to see their clothing stats and strategy",
    "competitors.placeholder": "Enter competitor Group ID (e.g. 114200141)",
    "competitors.analyze": "Analyze",
    "competitors.members": "Members",
    "competitors.clothingItems": "Clothing Items",
    "competitors.avgPrice": "Avg Price",
    "competitors.totalFavorites": "Total Favorites",
    "competitors.breakdown": "Clothing Breakdown",
    "competitors.shirts": "Shirts",
    "competitors.pants": "Pants",
    "competitors.tshirts": "T-Shirts",
    "competitors.priceAnalytics": "Price Analytics",
    "competitors.medianPrice": "Median Price",
    "competitors.minPrice": "Min Price",
    "competitors.maxPrice": "Max Price",
    "competitors.avgFavorites": "Avg Favorites",
    "competitors.created": "Created",
    "competitors.freeVsPaid": "Free vs Paid",
    "competitors.paid": "Paid",
    "competitors.freeOffsale": "Free / Off-sale",
    "competitors.priceDist": "Price Distribution",
    "competitors.free": "Free",
    "competitors.top5": "Top 5 Most Popular",
    "competitors.topClothing": "Top Clothing Items",
    "competitors.allClothing": "All Clothing",
    "competitors.showTop15": "Show Top 15",
    "competitors.showAll": "Show All",
    "competitors.loadMore": "Load more",
    "competitors.remaining": "remaining",
    "competitors.noItems": "No items found",
    "competitors.open": "Open",
    "competitors.closed": "Closed",
    "competitors.byFavorites": "By Favorites",
    "competitors.all": "All",
    "competitors.offsale": "Off-sale",

    "community.feed": "Feed",
    "community.discover": "Discover",
    "community.friends": "Friends",
    "community.messages": "Messages",
    "community.title": "Community",
    "community.desc": "Connect with other Roblox developers",
    "community.newPost": "What's new?",
    "community.post": "Post",
    "community.comment": "Comment",
    "community.comments": "Comments",
    "community.noComments": "No comments yet. Be the first!",
    "community.writeComment": "Write a comment...",
    "community.addFriend": "Add Friend",
    "community.friendsCheck": "Friends ✓",
    "community.requestSent": "Request Sent",
    "community.acceptRequest": "Accept Request",
    "community.friendSent": "Friend request sent!",
    "community.unfriended": "Unfriended",
    "community.friendAdded": "Friend added!",
    "community.chat": "Chat",
    "community.viewRoblox": "View on Roblox",
    "community.groups": "Groups",
    "community.posts": "Posts",
    "community.noShared": "This developer hasn't shared anything yet.",
    "community.profileNotFound": "Profile not found",
    "community.noPosts": "No posts yet. Share something!",
    "community.searchUsers": "Search developers...",
    "community.noUsersFound": "No users found",
    "community.noFriends": "No friends yet. Send a request in the Discover tab!",
    "community.noMessages": "No messages yet. Start a conversation with friends!",
    "community.typeMessage": "Type a message...",
    "community.you": "You",
    "community.pending": "Pending",
    "community.accept": "Accept",
    "community.loading": "Setting up your community profile...",
    "community.forum": "Forum",
    "community.editBio": "Edit Bio",

    "assistant.title": "AI Assistant",
    "assistant.desc": "Roblox expert at your service",
    "assistant.clear": "Clear",
    "assistant.askAnything": "Ask me anything about Roblox",
    "assistant.capabilities": "Lua scripts, moderation policies, clothing strategies, Discord posts — I can help with it all.",
    "assistant.placeholder": "Ask anything about Roblox...",
    "assistant.error": "An error occurred. Please try again.",
    "assistant.chatMode": "Chat",
    "assistant.imageMode": "Image",
    "assistant.imagePlaceholder": "Describe the image...",
    "assistant.generating": "Generating image...",
    "assistant.downloadImage": "Download",
    "assistant.imageAttached": "Image attached",
    "assistant.attachImage": "Attach image",

    "sniper.catalogPrice": "Catalog",

    "group.overview": "Overview",
    "group.catalog": "Catalog",
    "group.clothing": "Clothing",
    "group.upload": "Upload",
    "group.alts": "Alts",
    "group.pnl": "P&L",
    "group.stats": "Group Stats",
    "group.funds": "Funds",
    "group.pending": "Pending",
    "group.revenue24h": "Revenue 24h",
    "group.sales24h": "Sales 24h",
    "group.joinPolicy": "Join Policy",
    "group.locked": "Locked",
    "group.notLocked": "Not Locked",
    "group.members": "members",
    "group.catalogSearch": "Catalog Search",
    "group.catalogSearch.desc": "Search Roblox marketplace clothing, copy or download templates.",
    "group.keyword": "Keyword...",
    "group.groupIdFilter": "Group ID filter",
    "group.search": "Search",
    "group.results": "results",
    "group.selected": "selected",
    "group.download": "Download",
    "group.selectAll": "Select All",
    "group.clear": "Clear",
    "group.copy": "Copy",
    "group.copied": "Copied!",
    "group.copyFailed": "Copy failed",
    "group.downloadFailed": "Download failed",
    "group.bulkDownload": "Bulk download",
    "group.noResults": "No results",
    "group.tryDifferent": "Try a different keyword or group ID.",
    "group.slowDown": "Slow down",
    "group.slowDown.desc": "Wait a few seconds between searches to avoid rate limits.",
    "group.searchFailed": "Search failed",
    "group.shirts": "Shirts",
    "group.pants": "Pants",
    "group.relevance": "Relevance",
    "group.mostFavourited": "Most Favourited",
    "group.bestselling": "Bestselling",
    "group.recentlyUpdated": "Recently Updated",
    "group.clothingTab": "Group Clothing",
    "group.clothingTab.desc": "Clothing created by your group.",
    "group.uploadTab": "Upload Clothing",
    "group.uploadTab.desc": "Upload clothing to your group.",
    "group.uploadName": "Name",
    "group.uploadDesc": "Description",
    "group.uploadType": "Type",
    "group.uploadPrice": "Price",
    "group.uploadBtn": "Upload",
    "group.uploading": "Uploading...",
    "group.uploadSuccess": "Uploaded!",
    "group.uploadFailed": "Upload failed",
    "group.uploadAccount": "Upload account",
    "group.mainAccount": "Main account",
    "group.bulkName": "Bulk Name",
    "group.bulkType": "Bulk Type",
    "group.bulkPrice": "Bulk Price",
    "group.bulkDesc": "Bulk Description",
    "group.apply": "Apply",
    "group.template": "Template",
    "group.removeTemplate": "Remove Template",
    "group.altsTab": "Alt Accounts",
    "group.altsTab.desc": "Manage alternate accounts in your group.",
    "group.addAlt": "Add Alt",
    "group.removeAlt": "Remove Alt",
    "group.refreshAlts": "Refresh",

    "pnl.title": "Profit & Loss",
    "pnl.revenue": "Revenue",
    "pnl.sales": "Sales",
    "pnl.period": "Period",
    "pnl.daily": "Daily",
    "pnl.weekly": "Weekly",
    "pnl.monthly": "Monthly",
    "pnl.noData": "No data for the selected period.",
    "pnl.balance": "Balance",
    "pnl.pending": "Pending",
    "pnl.today": "Today",
    "pnl.net7d": "Net (7d)",
    "pnl.weekRevenue": "Week Gross Revenue",
    "pnl.commission": "Roblox Commission (30%)",
    "pnl.netFiat": "Net in Fiat",
    "pnl.monthRevenue": "Month Revenue",
    "pnl.monthLabel": "month",
    "pnl.topItems": "Top Items by Revenue",
    "pnl.recentTx": "Recent Transactions",
    "group.failedLoad": "Failed to load group stats.",
  },
  es: {
    "settings": "Configuración",
    "settings.desc": "Gestiona tu cuenta, apariencia y preferencias.",
    "settings.profile": "Perfil",
    "settings.appearance": "Apariencia",
    "settings.notifications": "Notificaciones",
    "settings.privacy": "Privacidad",
    "settings.data": "Datos",
    "settings.license": "Licencia",
    "settings.about": "Acerca de",
    "settings.language": "Idioma",
    "profile.title": "Tu perfil",
    "profile.desc": "Tu identidad de Roblox y presencia comunitaria.",
    "profile.bio": "Bio de comunidad",
    "profile.bio.placeholder": "Cuéntale a otros desarrolladores sobre ti...",
    "profile.bio.save": "Guardar bio",
    "profile.bio.saved": "¡Bio guardado!",
    "profile.bio.saved.desc": "Tu perfil de comunidad ha sido actualizado.",
    "profile.view": "Ver en Roblox ↗",
    "profile.session": "Acciones de sesión",
    "profile.disconnect": "Desconectar cuenta de Roblox",
    "profile.revoke": "Revocar clave de licencia",
    "appearance.theme": "Tema",
    "appearance.theme.desc": "Elige cómo se ve Limited.Ink para ti.",
    "appearance.light": "Claro",
    "appearance.dark": "Oscuro",
    "appearance.system": "Sistema",
    "appearance.active": "Activo",
    "appearance.interface": "Interfaz",
    "appearance.compact": "Modo compacto",
    "appearance.compact.desc": "Reducir el espaciado para más contenido en pantalla.",
    "appearance.autorefresh": "Auto-actualizar ventas",
    "appearance.autorefresh.desc": "Actualizar automáticamente los datos de ventas cada 30 segundos.",
    "notif.title": "Notificaciones",
    "notif.desc": "Controla cómo recibes notificaciones.",
    "notif.sound": "Efectos de sonido",
    "notif.sound.desc": "Reproducir sonidos para acciones y eventos.",
    "notif.sound.test": "Prueba",
    "notif.upload": "Notificaciones de subida",
    "notif.upload.desc": "Mostrar notificaciones al subir ropa.",
    "notif.chat": "Notificaciones de chat",
    "notif.chat.desc": "Mostrar notificaciones de nuevos mensajes.",
    "privacy.title": "Privacidad",
    "privacy.desc": "Controla tu visibilidad en la plataforma.",
    "privacy.discover": "Mostrar perfil en Descubrir",
    "privacy.discover.desc": "Permitir que otros desarrolladores te encuentren en la pestaña Comunidad.",
    "privacy.groups": "Mostrar mis grupos",
    "privacy.groups.desc": "Mostrar tus grupos de Roblox en tu perfil comunitario.",
    "privacy.friends": "Permitir solicitudes de amistad",
    "privacy.friends.desc": "Permitir que otros te envíen solicitudes de amistad.",
    "privacy.security": "Información de seguridad",
    "privacy.cookie": "Seguridad de Cookie",
    "privacy.cookie.desc": "Tu cookie de Roblox se almacena en una sesión cifrada del servidor (PostgreSQL, 7 días) y se elimina al desconectar.",
    "privacy.protected": "Protegido por licencia",
    "privacy.protected.desc": "Todos los endpoints API están protegidos por tu clave de licencia. El acceso no autorizado está bloqueado.",
    "data.export": "Exportar tus datos",
    "data.export.desc": "Descarga una copia de tus configuraciones y datos guardados.",
    "data.export.btn": "Exportar datos (JSON)",
    "data.exported": "¡Exportado!",
    "data.exported.desc": "Tus datos se han guardado como archivo JSON.",
    "data.local": "Almacenamiento local",
    "data.local.desc": "Gestiona los datos almacenados en este dispositivo.",
    "data.prefs": "Preferencias de interfaz",
    "data.prefs.desc": "Tema, estados de pestañas y más",
    "data.reset": "Restablecer",
    "data.cleared": "Limpiado",
    "data.cleared.desc": "Las preferencias de interfaz se han restablecido.",
    "license.title": "Información de licencia",
    "license.desc": "Detalles de tu plan actual de Limited.Ink.",
    "license.plan": "Plan",
    "license.status": "Estado",
    "license.active": "Activa",
    "license.invalid": "Inválida",
    "license.expires": "Expira",
    "license.upgrade": "Mejorar tu plan",
    "license.upgrade.desc": "Obtén acceso a más funciones con un plan superior.",
    "about.version": "Versión",
    "about.env": "Entorno",
    "about.footer": "Limited.Ink — Plataforma profesional de gestión de grupos de Roblox",
    "lang.title": "Idioma de la interfaz",
    "lang.desc": "Elige el idioma para la interfaz de Limited.Ink.",
    "lang.ru": "Русский",
    "lang.en": "English",
    "lang.es": "Español",
    "characters": "caracteres",

    "nav.profile": "Mi perfil",
    "nav.community": "Comunidad",
    "nav.tools": "Herramientas",
    "nav.assistant": "Asistente IA",
    "nav.competitors": "Competidores",
    "nav.sniper": "Sniper de limitados",
    "nav.groups": "Tus grupos",
    "nav.settings": "Configuración",
    "nav.license": "Licencia",
    "nav.disconnect": "Desconectar",
    "nav.revoke": "Revocar",
    "nav.members": "miembros",
    "nav.noGroups": "No se encontraron grupos.",

    "home.welcome": "Bienvenido a",
    "home.subtitle": "Selecciona un grupo del menú lateral — estadísticas, catálogo, análisis y más.",
    "home.groupMgmt": "Gestión de grupos",
    "home.catalogBrowser": "Catálogo",
    "home.salesAnalytics": "Análisis de ventas",
    "home.featured": "Grupos destacados",
    "home.featured.desc": "Grupos de Roblox usando Limited.Ink",
    "home.noFeatured": "Sin grupos destacados",
    "home.noFeatured.desc": "Los grupos que usan activamente Limited.Ink aparecerán aquí.",
    "home.members": "Miembros",
    "home.access": "Acceso",
    "home.public": "Público",
    "home.private": "Privado",
    "home.unknown": "Desconocido",
    "home.owner": "Propietario",
    "home.created": "Creado",
    "home.openRoblox": "Abrir en Roblox",
    "home.failedLoad": "Error al cargar información del grupo",

    "activation.title": "Activa tu licencia",
    "activation.desc": "Obtén tu código del bot de Telegram e introdúcelo abajo.",
    "activation.step1": "Abre Telegram",
    "activation.step1.desc": "Encuentra nuestro bot oficial",
    "activation.step2": "Envía /activate",
    "activation.step2.desc": "Solicita tu código de licencia",
    "activation.step3": "Introduce el código",
    "activation.step3.desc": "Pega y activa",
    "activation.botLink": "Abre el bot y escribe /activate",
    "activation.activate": "Activar dispositivo",
    "activation.verifying": "Verificando...",
    "activation.success": "Licencia activada",
    "activation.failed": "Error de activación",
    "activation.terms": "Al activar, aceptas los Términos de servicio y la Política de privacidad.",
    "activation.platform": "Plataforma profesional de Roblox",
    "activation.tagline": "Gestión de catálogo, herramientas de ropa y análisis de ventas — todo en un lugar.",
    "activation.features.catalog": "Herramienta de catálogo",
    "activation.features.analytics": "Análisis de ventas",
    "activation.features.alts": "Gestor de cuentas alt",
    "activation.features.featured": "Grupos destacados",

    "roblox.connect": "Conectar Roblox",
    "roblox.desc": "Tu cookie de sesión nos permite gestionar grupos y subir ropa en tu nombre.",
    "roblox.howTo": "Cómo obtener tu cookie",
    "roblox.step1": "Abre Roblox",
    "roblox.step1.desc": "Ve a roblox.com e inicia sesión",
    "roblox.step2": "F12 → Application",
    "roblox.step2.desc": "Abre DevTools, haz clic en \"Application\"",
    "roblox.step3": "Busca .ROBLOSECURITY",
    "roblox.step3.desc": "Cookies → roblox.com → copia el valor",
    "roblox.connectBtn": "Conectar cuenta",
    "roblox.connecting": "Conectando...",
    "roblox.connected": "¡Conectado!",
    "roblox.connectedAs": "Sesión como",
    "roblox.failed": "Error de conexión",
    "roblox.security": "Tu cookie se envía directamente a nuestro servidor y nunca se almacena en el navegador. La sesión expira en 7 días.",
    "roblox.privacy.title": "Tus datos son privados.",
    "roblox.privacy.desc": "Solo solicitamos los permisos mínimos para gestionar tus grupos y subir ropa.",
    "roblox.privacy.1": "Cookie nunca almacenada en tu navegador",
    "roblox.privacy.2": "Sesión cifrada en el servidor",
    "roblox.privacy.3": "Expira automáticamente en 7 días",
    "roblox.privacy.4": "Revoca el acceso en cualquier momento",

    "profile.friends": "Amigos",
    "profile.followers": "Seguidores",
    "profile.following": "Siguiendo",
    "profile.verified": "Verificado",
    "profile.banned": "Baneado",
    "profile.openRoblox": "Abrir en Roblox ↗",
    "profile.about": "Sobre mí",
    "profile.created": "Cuenta creada",
    "profile.failedLoad": "Error al cargar perfil.",

    "sniper.title": "Sniper de limitados",
    "sniper.desc": "Monitorea y compra objetos limitados de Roblox",
    "sniper.browse": "Explorar",
    "sniper.deals": "Ofertas",
    "sniper.watchlist": "Seguimiento",
    "sniper.search": "Buscar limitados...",
    "sniper.searchBtn": "Buscar",
    "sniper.deals.desc": "Objetos con valor superior al RAP o proyectados al alza",
    "sniper.refresh": "Actualizar",
    "sniper.watchlist.title": "Lista de seguimiento",
    "sniper.watchlist.desc": "Rastrea objetos y verifica precios para comprar.",
    "sniper.checkPrices": "Verificar precios",
    "sniper.pricesUpdated": "Precios actualizados",
    "sniper.addItems": "Agrega objetos desde Explorar u Ofertas para rastrearlos.",
    "sniper.target": "Objetivo",
    "sniper.live": "En vivo",
    "sniper.notForSale": "No en venta",
    "sniper.buy": "Comprar",
    "sniper.purchased": "¡Comprado!",
    "sniper.purchaseFailed": "Error de compra",

    "competitors.title": "Rastreador de competidores",
    "competitors.desc": "Analiza cualquier grupo de Roblox para ver sus estadísticas",
    "competitors.placeholder": "Introduce ID del grupo (ej. 114200141)",
    "competitors.analyze": "Analizar",
    "competitors.members": "Miembros",
    "competitors.clothingItems": "Artículos de ropa",
    "competitors.avgPrice": "Precio promedio",
    "competitors.totalFavorites": "Total favoritos",
    "competitors.breakdown": "Desglose de ropa",
    "competitors.shirts": "Camisas",
    "competitors.pants": "Pantalones",
    "competitors.tshirts": "Camisetas",
    "competitors.priceAnalytics": "Análisis de precios",
    "competitors.medianPrice": "Precio mediano",
    "competitors.minPrice": "Precio mín.",
    "competitors.maxPrice": "Precio máx.",
    "competitors.avgFavorites": "Prom. favoritos",
    "competitors.created": "Creado",
    "competitors.freeVsPaid": "Gratis vs Pago",
    "competitors.paid": "Pago",
    "competitors.freeOffsale": "Gratis / Sin venta",
    "competitors.priceDist": "Distribución de precios",
    "competitors.free": "Gratis",
    "competitors.top5": "Top 5 más populares",
    "competitors.topClothing": "Top de ropa",
    "competitors.allClothing": "Toda la ropa",
    "competitors.showTop15": "Mostrar top 15",
    "competitors.showAll": "Mostrar todo",
    "competitors.loadMore": "Cargar más",
    "competitors.remaining": "restantes",
    "competitors.noItems": "No se encontraron artículos",
    "competitors.open": "Abierto",
    "competitors.closed": "Cerrado",
    "competitors.byFavorites": "Por favoritos",
    "competitors.all": "Todos",
    "competitors.offsale": "Sin venta",

    "community.feed": "Muro",
    "community.discover": "Descubrir",
    "community.friends": "Amigos",
    "community.messages": "Mensajes",
    "community.title": "Comunidad",
    "community.desc": "Conecta con otros desarrolladores de Roblox",
    "community.newPost": "¿Qué hay de nuevo?",
    "community.post": "Publicar",
    "community.comment": "Comentar",
    "community.comments": "Comentarios",
    "community.noComments": "Sin comentarios. ¡Sé el primero!",
    "community.writeComment": "Escribe un comentario...",
    "community.addFriend": "Agregar amigo",
    "community.friendsCheck": "Amigos ✓",
    "community.requestSent": "Solicitud enviada",
    "community.acceptRequest": "Aceptar solicitud",
    "community.friendSent": "¡Solicitud de amistad enviada!",
    "community.unfriended": "Eliminado de amigos",
    "community.friendAdded": "¡Amigo agregado!",
    "community.chat": "Chat",
    "community.viewRoblox": "Ver en Roblox",
    "community.groups": "Grupos",
    "community.posts": "Publicaciones",
    "community.noShared": "Este desarrollador aún no ha compartido nada.",
    "community.profileNotFound": "Perfil no encontrado",
    "community.noPosts": "Sin publicaciones. ¡Comparte algo!",
    "community.searchUsers": "Buscar desarrolladores...",
    "community.noUsersFound": "No se encontraron usuarios",
    "community.noFriends": "Sin amigos. ¡Envía una solicitud en Descubrir!",
    "community.noMessages": "Sin mensajes. ¡Inicia una conversación!",
    "community.typeMessage": "Escribe un mensaje...",
    "community.you": "Tú",
    "community.pending": "Pendiente",
    "community.accept": "Aceptar",
    "community.loading": "Configurando tu perfil...",
    "community.forum": "Foro",
    "community.editBio": "Editar bio",

    "assistant.title": "Asistente IA",
    "assistant.desc": "Experto en Roblox a tu servicio",
    "assistant.clear": "Limpiar",
    "assistant.askAnything": "Pregúntame sobre Roblox",
    "assistant.capabilities": "Scripts Lua, políticas de moderación, estrategias de ropa, posts de Discord — puedo ayudar con todo.",
    "assistant.placeholder": "Pregunta lo que quieras sobre Roblox...",
    "assistant.error": "Ocurrió un error. Inténtalo de nuevo.",
    "assistant.chatMode": "Chat",
    "assistant.imageMode": "Imagen",
    "assistant.imagePlaceholder": "Describe la imagen...",
    "assistant.generating": "Generando imagen...",
    "assistant.downloadImage": "Descargar",
    "assistant.imageAttached": "Imagen adjunta",
    "assistant.attachImage": "Adjuntar imagen",

    "sniper.catalogPrice": "Catálogo",

    "group.overview": "Resumen",
    "group.catalog": "Catálogo",
    "group.clothing": "Ropa",
    "group.upload": "Subir",
    "group.alts": "Alts",
    "group.pnl": "P&L",
    "group.stats": "Estadísticas del grupo",
    "group.funds": "Fondos",
    "group.pending": "Pendiente",
    "group.revenue24h": "Ingresos 24h",
    "group.sales24h": "Ventas 24h",
    "group.joinPolicy": "Política de ingreso",
    "group.locked": "Bloqueado",
    "group.notLocked": "No bloqueado",
    "group.members": "miembros",
    "group.catalogSearch": "Búsqueda de catálogo",
    "group.catalogSearch.desc": "Busca ropa en el mercado de Roblox, copia o descarga plantillas.",
    "group.keyword": "Palabra clave...",
    "group.groupIdFilter": "ID de grupo",
    "group.search": "Buscar",
    "group.results": "resultados",
    "group.selected": "seleccionados",
    "group.download": "Descargar",
    "group.selectAll": "Seleccionar todo",
    "group.clear": "Limpiar",
    "group.copy": "Copiar",
    "group.copied": "¡Copiado!",
    "group.copyFailed": "Error al copiar",
    "group.downloadFailed": "Error al descargar",
    "group.bulkDownload": "Descarga masiva",
    "group.noResults": "Sin resultados",
    "group.tryDifferent": "Intenta otra palabra clave o ID de grupo.",
    "group.slowDown": "Más despacio",
    "group.slowDown.desc": "Espera unos segundos entre búsquedas.",
    "group.searchFailed": "Error de búsqueda",
    "group.shirts": "Camisas",
    "group.pants": "Pantalones",
    "group.relevance": "Relevancia",
    "group.mostFavourited": "Más favoritos",
    "group.bestselling": "Más vendidos",
    "group.recentlyUpdated": "Recientes",
    "group.clothingTab": "Ropa del grupo",
    "group.clothingTab.desc": "Ropa creada por tu grupo.",
    "group.uploadTab": "Subir ropa",
    "group.uploadTab.desc": "Sube ropa a tu grupo.",
    "group.uploadName": "Nombre",
    "group.uploadDesc": "Descripción",
    "group.uploadType": "Tipo",
    "group.uploadPrice": "Precio",
    "group.uploadBtn": "Subir",
    "group.uploading": "Subiendo...",
    "group.uploadSuccess": "¡Subido!",
    "group.uploadFailed": "Error al subir",
    "group.uploadAccount": "Cuenta para subir",
    "group.mainAccount": "Cuenta principal",
    "group.bulkName": "Nombre masivo",
    "group.bulkType": "Tipo masivo",
    "group.bulkPrice": "Precio masivo",
    "group.bulkDesc": "Descripción masiva",
    "group.apply": "Aplicar",
    "group.template": "Plantilla",
    "group.removeTemplate": "Eliminar plantilla",
    "group.altsTab": "Cuentas alt",
    "group.altsTab.desc": "Gestiona cuentas alternativas en tu grupo.",
    "group.addAlt": "Agregar alt",
    "group.removeAlt": "Eliminar alt",
    "group.refreshAlts": "Actualizar",

    "pnl.title": "Ganancias y pérdidas",
    "pnl.revenue": "Ingresos",
    "pnl.sales": "Ventas",
    "pnl.period": "Período",
    "pnl.daily": "Diario",
    "pnl.weekly": "Semanal",
    "pnl.monthly": "Mensual",
    "pnl.noData": "Sin datos para el período seleccionado.",
    "pnl.balance": "Saldo",
    "pnl.pending": "Pendiente",
    "pnl.today": "Hoy",
    "pnl.net7d": "Neto (7d)",
    "pnl.weekRevenue": "Ingresos de la semana",
    "pnl.commission": "Comisión Roblox (30%)",
    "pnl.netFiat": "Neto en fiat",
    "pnl.monthRevenue": "Ingresos del mes",
    "pnl.monthLabel": "mes",
    "pnl.topItems": "Top artículos por ingresos",
    "pnl.recentTx": "Transacciones recientes",
    "group.failedLoad": "Error al cargar datos del grupo.",
  },
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "ru",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("limitedink_lang");
    if (saved === "en" || saved === "es" || saved === "ru") return saved;
    return "ru";
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("limitedink_lang", l);
  }, []);

  const t = useCallback((key: string) => {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
