import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Lang = "ru" | "en" | "es";

const translations: Record<Lang, Record<string, string>> = {
  ru: {
    "settings": "Настройки",
    "settings.desc": "Управление аккаунтом, внешним видом и настройками.",
    "settings.profile": "Профиль",
    "settings.appearance": "Внешний вид",
    "settings.notifications": "Уведомления",
    "settings.privacy": "Приватность",
    "settings.data": "Данные",
    "settings.license": "Лицензия",
    "settings.about": "О нас",
    "settings.language": "Язык",
    "profile.title": "Ваш профиль",
    "profile.desc": "Ваша личность Roblox и присутствие в сообществе.",
    "profile.bio": "Био для сообщества",
    "profile.bio.placeholder": "Расскажите другим разработчикам о себе...",
    "profile.bio.save": "Сохранить био",
    "profile.bio.saved": "Био сохранено!",
    "profile.bio.saved.desc": "Ваш профиль в сообществе обновлён.",
    "profile.view": "Смотреть на Roblox ↗",
    "profile.session": "Действия с сессией",
    "profile.disconnect": "Отключить аккаунт Roblox",
    "profile.revoke": "Отозвать лицензионный ключ",
    "appearance.theme": "Тема",
    "appearance.theme.desc": "Выберите, как выглядит Limited.Ink для вас.",
    "appearance.light": "Светлая",
    "appearance.dark": "Тёмная",
    "appearance.system": "Система",
    "appearance.active": "Активна",
    "appearance.interface": "Интерфейс",
    "appearance.compact": "Компактный режим",
    "appearance.compact.desc": "Уменьшить отступы для большего контента на экране.",
    "appearance.autorefresh": "Авто-обновление продаж",
    "appearance.autorefresh.desc": "Автоматически обновлять данные продаж каждые 30 секунд.",
    "notif.title": "Уведомления",
    "notif.desc": "Настройте способ уведомлений.",
    "notif.sound": "Звуковые эффекты",
    "notif.sound.desc": "Воспроизводить звуки для действий и событий.",
    "notif.sound.test": "Тест",
    "notif.upload": "Уведомления о загрузке",
    "notif.upload.desc": "Показывать уведомления при загрузке одежды.",
    "notif.chat": "Уведомления чата",
    "notif.chat.desc": "Показывать уведомления о новых сообщениях.",
    "privacy.title": "Приватность",
    "privacy.desc": "Управление вашей видимостью на платформе.",
    "privacy.discover": "Показывать профиль в Обзоре",
    "privacy.discover.desc": "Позволить другим разработчикам находить вас во вкладке Сообщество.",
    "privacy.groups": "Показывать мои группы",
    "privacy.groups.desc": "Отображать ваши группы Roblox в профиле сообщества.",
    "privacy.friends": "Разрешить запросы в друзья",
    "privacy.friends.desc": "Позволить другим отправлять вам запросы в друзья.",
    "privacy.security": "Информация о безопасности",
    "privacy.cookie": "Безопасность Cookie",
    "privacy.cookie.desc": "Ваш Roblox cookie хранится в зашифрованной серверной сессии (PostgreSQL, 7 дней) и удаляется при отключении.",
    "privacy.protected": "Защита лицензией",
    "privacy.protected.desc": "Все API-эндпоинты защищены вашим лицензионным ключом. Неавторизованный доступ заблокирован.",
    "data.export": "Экспорт данных",
    "data.export.desc": "Скачайте копию ваших настроек и сохранённых данных.",
    "data.export.btn": "Экспортировать данные (JSON)",
    "data.exported": "Экспортировано!",
    "data.exported.desc": "Ваши данные сохранены как JSON файл.",
    "data.local": "Локальное хранилище",
    "data.local.desc": "Управление данными на этом устройстве.",
    "data.prefs": "Настройки интерфейса",
    "data.prefs.desc": "Тема, состояния вкладок и другое",
    "data.reset": "Сбросить",
    "data.cleared": "Очищено",
    "data.cleared.desc": "Настройки интерфейса были сброшены.",
    "license.title": "Информация о лицензии",
    "license.desc": "Детали вашего текущего плана Limited.Ink.",
    "license.plan": "План",
    "license.status": "Статус",
    "license.active": "Активна",
    "license.invalid": "Недействительна",
    "license.expires": "Истекает",
    "license.upgrade": "Улучшить план",
    "license.upgrade.desc": "Получите доступ к большему количеству функций с более высоким тарифом.",
    "about.version": "Версия",
    "about.env": "Среда",
    "about.footer": "Limited.Ink — Профессиональная платформа управления группами Roblox",
    "lang.title": "Язык интерфейса",
    "lang.desc": "Выберите язык для интерфейса Limited.Ink.",
    "lang.ru": "Русский",
    "lang.en": "English",
    "lang.es": "Español",
    "characters": "символов",
  },
  en: {
    "settings": "Settings",
    "settings.desc": "Manage your account, appearance, and preferences.",
    "settings.profile": "Profile",
    "settings.appearance": "Appearance",
    "settings.notifications": "Notifications",
    "settings.privacy": "Privacy & Security",
    "settings.data": "Data & Storage",
    "settings.license": "License",
    "settings.about": "About",
    "settings.language": "Language",
    "profile.title": "Your Profile",
    "profile.desc": "Your Roblox identity and community presence.",
    "profile.bio": "Community Bio",
    "profile.bio.placeholder": "Tell other developers about yourself...",
    "profile.bio.save": "Save Bio",
    "profile.bio.saved": "Bio saved!",
    "profile.bio.saved.desc": "Your community profile has been updated.",
    "profile.view": "View on Roblox ↗",
    "profile.session": "Session Actions",
    "profile.disconnect": "Disconnect Roblox Account",
    "profile.revoke": "Revoke License Key",
    "appearance.theme": "Theme",
    "appearance.theme.desc": "Choose how Limited.Ink looks for you.",
    "appearance.light": "Light",
    "appearance.dark": "Dark",
    "appearance.system": "System",
    "appearance.active": "Active",
    "appearance.interface": "Interface",
    "appearance.compact": "Compact Mode",
    "appearance.compact.desc": "Reduce spacing for more content on screen.",
    "appearance.autorefresh": "Auto-refresh Sales",
    "appearance.autorefresh.desc": "Automatically refresh sales data every 30 seconds.",
    "notif.title": "Notifications",
    "notif.desc": "Control how you get notified.",
    "notif.sound": "Sound Effects",
    "notif.sound.desc": "Play sounds for actions and events.",
    "notif.sound.test": "Test",
    "notif.upload": "Upload Notifications",
    "notif.upload.desc": "Show toast notifications for clothing uploads.",
    "notif.chat": "Chat Notifications",
    "notif.chat.desc": "Show notifications for new messages.",
    "privacy.title": "Privacy",
    "privacy.desc": "Control your visibility on the platform.",
    "privacy.discover": "Show Profile in Discover",
    "privacy.discover.desc": "Let other developers find you in the Community tab.",
    "privacy.groups": "Show My Groups",
    "privacy.groups.desc": "Display your Roblox groups on your community profile.",
    "privacy.friends": "Allow Friend Requests",
    "privacy.friends.desc": "Let others send you friend requests.",
    "privacy.security": "Security Info",
    "privacy.cookie": "Cookie Security",
    "privacy.cookie.desc": "Your Roblox cookie is stored in an encrypted server session (PostgreSQL-backed, 7-day TTL) and is cleared when you disconnect.",
    "privacy.protected": "License Protected",
    "privacy.protected.desc": "All API endpoints are protected by your license key. Unauthorized access is blocked.",
    "data.export": "Export Your Data",
    "data.export.desc": "Download a copy of your settings and saved prompts.",
    "data.export.btn": "Export Data as JSON",
    "data.exported": "Exported!",
    "data.exported.desc": "Your data has been saved as a JSON file.",
    "data.local": "Local Storage",
    "data.local.desc": "Manage data stored locally on this device.",
    "data.prefs": "UI Preferences",
    "data.prefs.desc": "Theme, tab states, and more",
    "data.reset": "Reset",
    "data.cleared": "Cleared",
    "data.cleared.desc": "UI preferences have been reset.",
    "license.title": "License Information",
    "license.desc": "Details about your current Limited.Ink plan.",
    "license.plan": "Plan",
    "license.status": "Status",
    "license.active": "Active",
    "license.invalid": "Invalid",
    "license.expires": "Expires",
    "license.upgrade": "Upgrade Your Plan",
    "license.upgrade.desc": "Get access to more features with a higher tier plan.",
    "about.version": "Version",
    "about.env": "Environment",
    "about.footer": "Limited.Ink — Professional Roblox Group Management Platform",
    "lang.title": "Interface Language",
    "lang.desc": "Choose the language for the Limited.Ink interface.",
    "lang.ru": "Русский",
    "lang.en": "English",
    "lang.es": "Español",
    "characters": "characters",
  },
  es: {
    "settings": "Configuración",
    "settings.desc": "Gestiona tu cuenta, apariencia y preferencias.",
    "settings.profile": "Perfil",
    "settings.appearance": "Apariencia",
    "settings.notifications": "Notificaciones",
    "settings.privacy": "Privacidad",
    "settings.data": "Datos",
    "settings.license": "Licencia",
    "settings.about": "Acerca de",
    "settings.language": "Idioma",
    "profile.title": "Tu perfil",
    "profile.desc": "Tu identidad de Roblox y presencia comunitaria.",
    "profile.bio": "Bio de comunidad",
    "profile.bio.placeholder": "Cuéntale a otros desarrolladores sobre ti...",
    "profile.bio.save": "Guardar bio",
    "profile.bio.saved": "¡Bio guardado!",
    "profile.bio.saved.desc": "Tu perfil de comunidad ha sido actualizado.",
    "profile.view": "Ver en Roblox ↗",
    "profile.session": "Acciones de sesión",
    "profile.disconnect": "Desconectar cuenta de Roblox",
    "profile.revoke": "Revocar clave de licencia",
    "appearance.theme": "Tema",
    "appearance.theme.desc": "Elige cómo se ve Limited.Ink para ti.",
    "appearance.light": "Claro",
    "appearance.dark": "Oscuro",
    "appearance.system": "Sistema",
    "appearance.active": "Activo",
    "appearance.interface": "Interfaz",
    "appearance.compact": "Modo compacto",
    "appearance.compact.desc": "Reducir el espaciado para más contenido en pantalla.",
    "appearance.autorefresh": "Auto-actualizar ventas",
    "appearance.autorefresh.desc": "Actualizar automáticamente los datos de ventas cada 30 segundos.",
    "notif.title": "Notificaciones",
    "notif.desc": "Controla cómo recibes notificaciones.",
    "notif.sound": "Efectos de sonido",
    "notif.sound.desc": "Reproducir sonidos para acciones y eventos.",
    "notif.sound.test": "Prueba",
    "notif.upload": "Notificaciones de subida",
    "notif.upload.desc": "Mostrar notificaciones al subir ropa.",
    "notif.chat": "Notificaciones de chat",
    "notif.chat.desc": "Mostrar notificaciones de nuevos mensajes.",
    "privacy.title": "Privacidad",
    "privacy.desc": "Controla tu visibilidad en la plataforma.",
    "privacy.discover": "Mostrar perfil en Descubrir",
    "privacy.discover.desc": "Permitir que otros desarrolladores te encuentren en la pestaña Comunidad.",
    "privacy.groups": "Mostrar mis grupos",
    "privacy.groups.desc": "Mostrar tus grupos de Roblox en tu perfil comunitario.",
    "privacy.friends": "Permitir solicitudes de amistad",
    "privacy.friends.desc": "Permitir que otros te envíen solicitudes de amistad.",
    "privacy.security": "Información de seguridad",
    "privacy.cookie": "Seguridad de Cookie",
    "privacy.cookie.desc": "Tu cookie de Roblox se almacena en una sesión cifrada del servidor (PostgreSQL, 7 días) y se elimina al desconectar.",
    "privacy.protected": "Protegido por licencia",
    "privacy.protected.desc": "Todos los endpoints API están protegidos por tu clave de licencia. El acceso no autorizado está bloqueado.",
    "data.export": "Exportar tus datos",
    "data.export.desc": "Descarga una copia de tus configuraciones y datos guardados.",
    "data.export.btn": "Exportar datos (JSON)",
    "data.exported": "¡Exportado!",
    "data.exported.desc": "Tus datos se han guardado como archivo JSON.",
    "data.local": "Almacenamiento local",
    "data.local.desc": "Gestiona los datos almacenados en este dispositivo.",
    "data.prefs": "Preferencias de interfaz",
    "data.prefs.desc": "Tema, estados de pestañas y más",
    "data.reset": "Restablecer",
    "data.cleared": "Limpiado",
    "data.cleared.desc": "Las preferencias de interfaz se han restablecido.",
    "license.title": "Información de licencia",
    "license.desc": "Detalles de tu plan actual de Limited.Ink.",
    "license.plan": "Plan",
    "license.status": "Estado",
    "license.active": "Activa",
    "license.invalid": "Inválida",
    "license.expires": "Expira",
    "license.upgrade": "Mejorar tu plan",
    "license.upgrade.desc": "Obtén acceso a más funciones con un plan superior.",
    "about.version": "Versión",
    "about.env": "Entorno",
    "about.footer": "Limited.Ink — Plataforma profesional de gestión de grupos de Roblox",
    "lang.title": "Idioma de la interfaz",
    "lang.desc": "Elige el idioma para la interfaz de Limited.Ink.",
    "lang.ru": "Русский",
    "lang.en": "English",
    "lang.es": "Español",
    "characters": "caracteres",
  },
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "ru",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("limitedink_lang");
    if (saved === "en" || saved === "es" || saved === "ru") return saved;
    return "ru";
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("limitedink_lang", l);
  }, []);

  const t = useCallback((key: string) => {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
